### ISSUE TITLE
How to use in a script?

### ISSUE THREAD

**Issue by sofiabelen** [tichopad/alacritty-theme-switch#51]
Is there a way to pass the name of the theme as a variable, in order to use it in a script? (Instead of having to manually choose the theme with the arrows.)

I mean something like this:

`alacritty-theme-switch monokai`

**Comment by tichopad** [comment]
Hi!

sorry for the long silence. You can use the `--select` or `-s` flag and pass it path of the theme file relative to the themes' folder, e.g.:
```
alacritty-theme-switch --select monokai.yml
```

I'm going to update readme to make it more clear :+1:

**Comment by tichopad** [comment]
I'm going to close this. Let me know if you're having any issues by opening a new thread and I'll check it out!
